### ISSUE TITLE
Improve importing / creating of recipes

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#122]
Ideas where Ai can help in the creation of recipes:

* Upload an image to create a recipe
* Using AI to add extra information to a recipe when you publish
* Implement searching with embedding's using supabase functions

### Ways to import recipes

- [X] Manual creation 
- [X] Import via link
- [X] Import from text (copy from a doc) 
- [X] take a photo to import
- [ ] Mass imports? - could be from a bunch of photos or a list of links

### Tools to help:

* Rate limiting the API using [Upstash Rate limiting](https://github.com/upstash/ratelimit-js#ratelimiting-algorithms)
* Using Ai with [vercel ai sdk](https://sdk.vercel.ai/)
* Requesting AI through[ google generative AI ](https://ai.google.dev/gemini-api)using [google gemini 1.5 flash](https://deepmind.google/technologies/gemini/flash/)

## TODO

- [X]  add a disclaimer about copyright

- [ ] remove migrations from the folder and add them to gitignore
- [X] add a created-by-type to the recipe `"link" | "title" | "image" | "text"` 
- [X] figure out a better name for the recipe creation type `text` as it's really pasting in information 
- [X] test the image creation to make sure it fails on non-recipe types
- [X] for the HTML parser use a [dynamic import for a library](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#loading-external-libraries)

[https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#importing-named-exports](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#importing-named-exports)
