### ISSUE TITLE
Redesign of landing page

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#147]
The main landing page is lacking greatly and would be great to not only show just recipes but features, top recipes, etc.<br><br>While the landing page is pretty good it would be great to make it similar while being easy to find everything you want

## TODO

- [ ] Research
  - [ ] recipe landing pages
  - [ ] books
  - [ ] feature sections
- [ ] Build wireframe
- [ ] Build the layout and design
- [ ] Make sure it is beautiful in light mode and responsive
