### ISSUE TITLE
Moodboard of Mixie design

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#154]
Mixie's goal is to be a place where you can cook, create and collaborate. somewhere that is safe, warm and homey. <br><br>A platform where you can share your grandma's cookbook with those that you love and possibly with the world.

## Todo:

- [ ] Search and create mood board:
  - [ ] Top kitchen sets
  - [ ] Top kitchen designs
  - [ ] Top living room designs
  - [ ] Home
- [ ] Grab inspiration for
  - [ ] Homey designs
  - [ ] Warm designs
  - [ ] Safe designs
- [ ] look into top brands that do similar things around my goal:
  - [ ] AirBnB - bringing people into other homes
  - [ ] Arc browser - a browser for the every day, warm, homey
  - [ ] Other companies
