### ISSUE TITLE
Restructure Project

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#159]
As Mixie has grown more and more it has gotten harder to manage and support new features along the way. in this restructure we are going to separate parts that are needed, move components around, reinstall parts and so much more. 

### TODO

- [ ] Init the project
- [ ] Rebuild the structure separating parts that need to separated
- [ ] Add Web - Nextjs
- [ ] Add Mobile - [Expo](https://expo.dev/)
- [ ] Add docs - [Fumadocs](https://fumadocs.vercel.app/)
