### ISSUE TITLE
Build onboarding flow

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#167]
As Mixie grows to build out the social factor it would be great that new users can customise their profile without going to the settings page.

## TODO

- [ ] Show onboarding page for new users
- [ ] Show features page after onboarding
- [ ] Improve the settings page to represent these onboard changes
