### ISSUE TITLE
Critical Fixes

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#168]
To release this new feature we need to power through the top priority items.

## TODO

- [ ] [MIX-167](https://linear.app/jacobsamo/issue/MIX-167/fix-recipe-creations-failing) 
- [X] images are not saved on form
- [X] Clicking on a card should take you to the recipe rather than just the title
- [X] next/back button for search doesn't work
- [ ] When you click on the edit button of a recipe it doesn't auto-fill 
- [ ] More logging across the board
