### ISSUE TITLE
Fix Recipe creations failing

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#169]
Currently, Mixie's recipe creation methods fail more often than not.

| Method | Sucess rate | How they work |
| -- | -- | -- |
| Title | 100% | Simple form |
| Link | 20% | Algorithm  |
| Image | 50% | AI |
| Paste | 0% | AI |

### TODO

- [ ] Fix AI features failing
- [ ] Improve error management - make it super easy to understand errors 
- [ ] improve logging so we have more data to understand what the hell is happening
  - [ ] Implment a logging service - vercel as removed there log drains on hobby plans
  - [ ] Add data services like tinybird, etc
- [X] Fix creation via links failing
- [ ] text searching to use fuzzy searching

## AI features

Think these are failing due to using `generateText` and then custom parsing content to JSON rather than using `generateObject`, will have to sacifes if someone pastes in a non recipe with something like: `if (!steps || !ingredients)` than just create with the title otherwise if they are included then create with all information.

Could add a cause for the ai saying: "If content is not a image return null" than everything should be null.

**ToDO**

- [ ] Change to `generateObject`
- [ ] Add logging in for it no matter what level we need to monitor this

## Links

Not picking up the `@Recipe` from the content at all so might need to do something like this:

```javascript
if (data.includes("@Recipe")) {
  // contuine with parsing step
} else {
// skip this step
contuine;
}
```

could do some other better parsing methods too
