### ISSUE TITLE
MVP bug fixes

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#177]
List of all bug features that need fixing from the MVP

### TODO

- [ ] Finding recipe images is really hard
- [ ] Adding more information to API responses, especially on error.
- [ ] Being logged out quite regularly 
- [ ] Baselime logging failing
- [X] Light mode still sucks
- [X] On models that have multi options the back arrow makes it something like: "< back"
- [X] Any inputs using `setValue` doesn't change dirty state

- [X] Photographer links from unsplash to include `/?utm_source=mixie&utm_medium=referral` as this is needed apart of the unspalsh developer API requirements which we are doing for the Unsplash but on the photographer

**Recipe creation**

- [ ] Image upload fails quite often
  - [ ] Upload the whole file and save to DB
- [X] Still doesn't quite grab recipes from URL's still
