### ISSUE TITLE
Improve Image uploads on recipes

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#178]
At the moment finding images for recipes is really hard to do, we want to improve this so that users don't upload recipes without images or low quality ones. 

### Things to look into

- [ ] Using AI image generation 
- [ ] Copyright free images platforms link Unsplash

## TODO

- [ ]  Improve the modal
