### ISSUE TITLE
Fix recipe creation failing

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#182]
Currently, recipe creation tends to fail for various of reasons the main ones being:

* import from website
* upload an image

Something that I have noticed is that the button doesn't click for some reason 

## TODO

- [X] Make sure the button works first go 
  - [X] if there is a form error, show it

### Upload an image

- [X] Handle all popular image formats (.webp, .jpg, .png, .heic, etc)
  - [X] Convert each image to a jpg
- [X] Upload the image to Supabase
