### ISSUE TITLE
Full coverage through logging

### ISSUE THREAD

**Issue by jacobsamo** [jacobsamo/Mixie#183]
So we have tried various forms of logging including; baseline, Vercel, Axiom, and Posthog. currently we are using Posthog for analytics and client-side tracking.

Baselime wasn't working due to the transport feature in pino, would be great to see if we can fix that, if not we need to figure out a good logging provider to guarantee 100% coverage of logs in the app and all errors to be logged for us.

## TODO

- [X] Research the best free logging platforms
  - [X] choose one that is free
  - [X] high-speed logging (next-axiom takes up to 150ms needs to be quicker than that)
- [X] Log client-side errors in forms - make sure this is meaningful 

### Posthog

- [X] identify users by userId if signed in
- [ ] see if we can use capture groups using `posthog.capture()`
